const seedTenders = [
  { id: 1, initials: 'NC', client: 'Northstar Community Hub', owner: 'Bristol City Council', stage: 'In progress', statusClass: 'in-progress', due: '24 Sep 2026', isoDue: '2026-09-24', dueShort: '24', month: 'SEP', progress: 72, color: '#e4f2e9', ink: '#3f8a64' },
  { id: 2, initials: 'RC', client: 'Riverside Civic Centre', owner: 'Southwark Council', stage: 'Ready to submit', statusClass: 'ready', due: '02 Oct 2026', isoDue: '2026-10-02', dueShort: '02', month: 'OCT', progress: 94, color: '#e5eff7', ink: '#4f7c9a' },
  { id: 3, initials: 'WL', client: 'Westfield Library Extension', owner: 'Westfield Borough', stage: 'In review', statusClass: 'review', due: '08 Oct 2026', isoDue: '2026-10-08', dueShort: '08', month: 'OCT', progress: 48, color: '#fff0d8', ink: '#b47b33' },
  { id: 4, initials: 'GP', client: 'Greenway Park Pavilion', owner: 'Haringey Council', stage: 'Draft', statusClass: 'draft', due: '21 Oct 2026', isoDue: '2026-10-21', dueShort: '21', month: 'OCT', progress: 21, color: '#eef0ee', ink: '#728179' },
  { id: 5, initials: 'MC', client: 'Meadowbrook Clinic', owner: 'NHS Property Services', stage: 'In progress', statusClass: 'in-progress', due: '04 Nov 2026', isoDue: '2026-11-04', dueShort: '04', month: 'NOV', progress: 35, color: '#fbeae5', ink: '#bd705e' },
  { id: 6, initials: 'EH', client: 'East Harbour Retrofit', owner: 'Port Authority', stage: 'Draft', statusClass: 'draft', due: '18 Nov 2026', isoDue: '2026-11-18', dueShort: '18', month: 'NOV', progress: 12, color: '#e8edf5', ink: '#6c7c9b' }
];
let tenders = JSON.parse(localStorage.getItem('bidroom-tenders') || 'null') || seedTenders;
let activeFilter = 'All status';
const $ = (selector) => document.querySelector(selector);
const modal = $('#modalBackdrop');
const modalContent = $('#modalContent');
function save() { localStorage.setItem('bidroom-tenders', JSON.stringify(tenders)); }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2600); }
function openModal(content) { modalContent.innerHTML = content; modal.hidden = false; document.body.style.overflow = 'hidden'; }
function closeModal() { modal.hidden = true; document.body.style.overflow = ''; }
function renderTenders() { const visible = tenders.filter(tender => activeFilter === 'All status' || tender.stage === activeFilter); $('#tenderRows').innerHTML = visible.map(tender => `<tr><td><div class="tender-name"><span class="tender-logo" style="background:${tender.color};color:${tender.ink}">${tender.initials}</span><span><strong>${tender.client}</strong><small>${tender.owner}</small></span></div></td><td><span class="status ${tender.statusClass}">${tender.stage}</span></td><td class="submission ${tender.progress > 70 ? '' : 'urgent'}">${tender.due}</td><td class="progress-cell"><div class="progress-line"><i style="width:${tender.progress}%"></i></div><small>${tender.progress}% complete</small></td><td><button class="row-menu" data-menu="${tender.id}" aria-label="Tender actions">•••</button></td></tr>`).join(''); $('#emptyState').hidden = visible.length > 0; $('#navTenderCount').textContent = tenders.length; $('#activeMetric').textContent = tenders.filter(t => t.stage !== 'Draft').length; $('#openTenderText').textContent = `${tenders.filter(t => t.stage !== 'Draft').length} active tenders`; $('#documentsMetric').textContent = Math.max(18, tenders.length * 3); document.querySelectorAll('[data-menu]').forEach(button => button.addEventListener('click', () => openTenderActions(Number(button.dataset.menu)))); }
function renderDeadlines() { $('#deadlineList').innerHTML = tenders.slice(0, 3).map(t => `<div class="deadline"><div class="date-block"><strong>${t.month}</strong><b>${t.dueShort}</b></div><div class="deadline-copy"><strong>${t.client}</strong><small>Submission due <em>${t.due}</em></small></div></div>`).join(''); }
function tenderForm(tender = {}) { return `<h2 id="modalTitle">${tender.id ? 'Edit tender' : 'Create a tender'}</h2><p class="modal-intro">Keep the important details close to hand.</p><form id="tenderForm"><div class="form-grid"><div class="field full"><label for="client">Tender name</label><input id="client" name="client" required placeholder="e.g. Northstar Community Hub" value="${tender.client || ''}" /></div><div class="field full"><label for="owner">Client / contracting authority</label><input id="owner" name="owner" required placeholder="e.g. Bristol City Council" value="${tender.owner || ''}" /></div><div class="field"><label for="stage">Current stage</label><select id="stage" name="stage"><option ${tender.stage === 'Draft' ? 'selected' : ''}>Draft</option><option ${tender.stage === 'In progress' ? 'selected' : ''}>In progress</option><option ${tender.stage === 'In review' ? 'selected' : ''}>In review</option><option ${tender.stage === 'Ready to submit' ? 'selected' : ''}>Ready to submit</option></select></div><div class="field"><label for="dueDate">Submission date</label><input id="dueDate" name="dueDate" type="date" required /></div><div class="field full"><label for="notes">Internal notes</label><textarea id="notes" name="notes" placeholder="Add a short note for your team...">${tender.notes || ''}</textarea></div></div><div class="form-actions"><button type="button" class="cancel-button" id="modalCancel">Cancel</button><button class="primary-button" type="submit">${tender.id ? 'Save changes' : 'Create tender'}</button></div></form>`; }
function openTenderForm(id) { const tender = tenders.find(item => item.id === id); openModal(tenderForm(tender)); if (tender) $('#dueDate').value = tender.isoDue || ''; $('#modalCancel').onclick = closeModal; $('#tenderForm').onsubmit = event => { event.preventDefault(); const data = new FormData(event.target); const date = new Date(`${data.get('dueDate')}T12:00:00`); const updated = { client: data.get('client'), owner: data.get('owner'), stage: data.get('stage'), notes: data.get('notes'), due: date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }), dueShort: date.getDate().toString().padStart(2, '0'), month: date.toLocaleDateString('en-US', { month: 'short' }).toUpperCase(), isoDue: data.get('dueDate'), progress: tender?.progress || 8, initials: data.get('client').split(' ').map(word => word[0]).slice(0, 2).join('').toUpperCase(), color: '#e4f2e9', ink: '#3f8a64', statusClass: data.get('stage') === 'Ready to submit' ? 'ready' : data.get('stage') === 'In review' ? 'review' : data.get('stage') === 'Draft' ? 'draft' : 'in-progress' }; if (id) tenders = tenders.map(item => item.id === id ? { ...item, ...updated } : item); else tenders.unshift({ id: Date.now(), ...updated }); save(); renderTenders(); renderDeadlines(); closeModal(); showToast(id ? 'Tender updated' : 'Tender created'); }; }
function openTenderActions(id) { const tender = tenders.find(item => item.id === id); openModal(`<h2>${tender.client}</h2><p class="modal-intro">${tender.owner} · due ${tender.due}</p><div class="form-actions" style="justify-content:flex-start;flex-wrap:wrap"><button class="primary-button" id="editTender">Edit details</button><button class="outline-button" id="uploadTender">Upload document</button><button class="cancel-button" id="deleteTender">Delete tender</button></div>`); $('#editTender').onclick = () => openTenderForm(id); $('#uploadTender').onclick = () => openUpload(id); $('#deleteTender').onclick = () => { tenders = tenders.filter(item => item.id !== id); save(); renderTenders(); renderDeadlines(); closeModal(); showToast('Tender deleted'); }; }
function openUpload(id) { const tender = tenders.find(item => item.id === id); openModal(`<h2>Upload to ${tender.client}</h2><p class="modal-intro">Store the latest bid files with the right tender.</p><div class="dropzone"><strong>Choose a document</strong><p>PDF, DOCX, XLSX or ZIP up to 25 MB</p><input id="fileInput" type="file" accept=".pdf,.docx,.xlsx,.zip" /></div><div class="form-actions"><button class="cancel-button" id="modalCancel">Cancel</button><button class="primary-button" id="uploadConfirm">Attach document</button></div>`); $('#modalCancel').onclick = closeModal; $('#uploadConfirm').onclick = () => { const file = $('#fileInput').files[0]; if (!file) return showToast('Choose a file first'); closeModal(); showToast(`${file.name} attached to ${tender.client}`); }; }
function openAi() { openModal(`<div class="ai-orbit">✦</div><h2>Bidroom AI assistant</h2><p class="modal-intro">Ask a question about your tender documents or get a quick bid plan.</p><div class="field"><label for="aiPrompt">What do you need to know?</label><textarea id="aiPrompt" placeholder="e.g. What are the key submission requirements?"></textarea></div><div class="form-actions"><button class="primary-button" id="askAi">Generate answer</button></div><div id="aiAnswer"></div>`); $('#askAi').onclick = () => { const prompt = $('#aiPrompt').value || 'the key submission requirements'; $('#aiAnswer').innerHTML = `<div class="ai-result"><strong>Here is a starting brief for “${prompt}”</strong><ul><li>Confirm the submission deadline and required file naming convention.</li><li>Assign an owner for the pricing schedule and quality response.</li><li>Check that insurance, case studies and declarations are current.</li></ul><span>Upload a tender document to make this answer specific to your bid.</span></div>`; }; }
function openAccount() { openModal(`<h2>Your account</h2><p class="modal-intro">Manage your Bidroom identity and workspace profile.</p><div class="account-panel"><span class="user-avatar">JD</span><div><strong id="accountDisplayName">Jordan Davis</strong><small>jordan@arcandco.studio</small></div></div><form id="accountForm"><div class="field"><label for="profileName">Display name</label><input id="profileName" value="Jordan Davis" /></div><div class="form-actions"><button type="button" class="cancel-button" id="modalCancel">Cancel</button><button class="primary-button">Save profile</button></div></form>`); $('#modalCancel').onclick = closeModal; $('#accountForm').onsubmit = event => { event.preventDefault(); const name = $('#profileName').value.trim() || 'Jordan Davis'; $('#userName').textContent = name; $('#accountDisplayName').textContent = name; $('#headerAccountButton').textContent = name.split(' ').map(w => w[0]).join('').slice(0, 2).toUpperCase(); closeModal(); showToast('Profile updated'); }; }
function openSearch() { openModal(`<h2>Search your workspace</h2><p class="modal-intro">Find a tender by name, client or stage.</p><div class="field"><label for="searchInput">Search</label><input id="searchInput" autofocus placeholder="e.g. Riverside or review" /></div><div id="searchResults" class="search-results"></div>`); const input = $('#searchInput'); const results = $('#searchResults'); const updateResults = () => { const query = input.value.trim().toLowerCase(); const matches = tenders.filter(t => !query || [t.client, t.owner, t.stage].some(value => value.toLowerCase().includes(query))); results.innerHTML = matches.length ? matches.map(t => `<button class="search-result" data-result="${t.id}" type="button"><span class="tender-logo" style="background:${t.color};color:${t.ink}">${t.initials}</span><span><strong>${t.client}</strong><small>${t.stage} · due ${t.due}</small></span></button>`).join('') : '<p class="search-empty">No matching tenders.</p>'; results.querySelectorAll('[data-result]').forEach(button => button.onclick = () => { closeModal(); activeFilter = 'All status'; $('#filterButton').innerHTML = 'All status <span>⌄</span>'; renderTenders(); document.querySelector('#tenders').scrollIntoView({ behavior: 'smooth' }); showToast(`${tenders.find(t => t.id === Number(button.dataset.result)).client} selected`); }); }; input.oninput = updateResults; updateResults(); }
function openNotifications() { openModal('<h2>Notifications</h2><p class="modal-intro">Recent updates from your bid desk.</p><div class="notification-list"><div><strong>Riverside Civic Centre is ready to submit</strong><small>Yesterday, 16:18</small></div><div><strong>Maria Chen uploaded technical-response.docx</strong><small>Today, 09:42</small></div><div><strong>Westfield Library Extension has a new comment</strong><small>Yesterday, 11:05</small></div></div>'); const indicator = $('.notification-button i'); if (indicator) indicator.remove(); }
function openWorkspace() { openModal('<h2>Arc &amp; Co. workspace</h2><p class="modal-intro">Choose the workspace you want to open.</p><div class="workspace-options"><button class="workspace-option" type="button"><span class="workspace-avatar">AC</span><span><strong>Arc &amp; Co.</strong><small>Current workspace</small></span><b>✓</b></button><button class="workspace-option" type="button"><span class="workspace-avatar">PC</span><span><strong>Parkside Collective</strong><small>Design workspace</small></span></button></div>'); document.querySelectorAll('.workspace-option').forEach(option => option.onclick = () => { closeModal(); showToast(`${option.querySelector('strong').textContent} selected`); }); }
function setup() { renderTenders(); renderDeadlines(); $('#newTenderButton').onclick = () => openTenderForm(); $('#emptyNewButton').onclick = () => openTenderForm(); $('#aiButton').onclick = openAi; $('#aiTipButton').onclick = openAi; $('#accountButton').onclick = openAccount; $('#headerAccountButton').onclick = openAccount; $('#searchButton').onclick = openSearch; $('#notificationButton').onclick = openNotifications; $('#workspaceButton').onclick = openWorkspace; $('#teamLink').onclick = event => { event.preventDefault(); showToast('Team workspace is ready to configure'); }; $('#settingsLink').onclick = event => { event.preventDefault(); showToast('Workspace settings are ready to configure'); }; $('#modalClose').onclick = closeModal; modal.addEventListener('click', event => { if (event.target === modal) closeModal(); }); $('#filterButton').onclick = () => { const options = ['All status', 'Draft', 'In progress', 'In review', 'Ready to submit']; activeFilter = options[(options.indexOf(activeFilter) + 1) % options.length]; $('#filterButton').innerHTML = `${activeFilter} <span>⌄</span>`; renderTenders(); }; $('#viewAllButton').onclick = () => { activeFilter = 'All status'; $('#filterButton').innerHTML = 'All status <span>⌄</span>'; renderTenders(); document.querySelector('#tenders').scrollIntoView({ behavior: 'smooth' }); }; $('#calendarButton').onclick = () => showToast('Calendar event creation is ready for your next deadline'); $('#calendarViewButton').onclick = () => showToast('Calendar view synced with your submission dates'); $('#activityButton').onclick = () => showToast('You are all caught up'); }
setup();